# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d32bc73f5aa287f39e1659e5dfb1c8327db5048a6c656cedb3e01e1d7a1e0602ee6a102618de52f3dcc6f53aa3762c66f86f79b1bb6f00d6b76026e0f17741b3

test:
  secret_key_base: df50369a0be4767ae8572d8bf694b63eda3f19b000908714d7d8f5a45fbd521bf7e3a7c4afefd57c4940bdb06ed49f2e53510bc0d0d4d44099b269158cfe20b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
